name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4 # Pin actions to specific versions for security

    # 2. Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # Location for the settings.xml file

    # 3. Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 4. Setup Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 7.6 # Specify the Gradle version to use
        cache-read-only: false # Enable caching for Gradle dependencies

    # 5. Validate Gradle wrapper
    - name: Validate Gradle Wrapper
      run: ./gradlew wrapper --validate

    # 6. Verify Gradle Installation
    - name: Verify Gradle Installation
      run: gradle --version

    # 7. Build with Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # 8. Publish to GitHub Packages
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
