name: Mobbscan Workflow

on:
  push:
    branches: # Include all branches
      - '**'
  pull_request:
    branches: # Include all branches for PRs
      - '**'

jobs:
  mobbscan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run MobbScan Action
      - name: Run MobbScan
        uses: mobb-dev/action@6c55ca0e860071725037e6dcf5b14040edd1d3ec # Pin to SHA instead of version for security
        with:
          report-file: results/sast-report.json  # Path to SAST report file
          api-key: ${{ secrets.MOBB_API_KEY }}  # Mobb API Key from GitHub Secrets
          github-token: ${{ secrets.GITHUB_TOKEN }} # GitHub Token from GitHub Secrets
          mobb-project-name: MyAndroidProject    # Optional: Project name
          auto-pr: true                          # Optional: Enable auto PR
          commit-directly: false                 # Optional: Do not commit directly
