            - name: mobbdev
  # You may pin to the exact commit or the version.
  # uses: mobb-dev/action@6c55ca0e860071725037e6dcf5b14040edd1d3ec
  uses: mobb-dev/action@v1.1
  with:
    # Path to SAST report file
    report-file: 
    # Mobb API key
    api-key: 
    # GitaHub Token
    github-token: 
    # Mobb Project Name
    mobb-project-name: # optional
    # Auto-PR flag
    auto-pr: # optional
    # Commit Directly flag, this requires Auto-PR flag to be set. Once enabled, Mobb will commit the fixes directly to the branch
    commit-directly: # optional
          
